website/kanikervanaf/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "",
        include(
            [
                path("v1/", include("kanikervanaf.api.v1.urls", namespace="v1")),
            ]
        ),
    ),  # noqa
    path(
        "docs",
        TemplateView.as_view(
            template_name="kanikervanaf/swagger.html",
            extra_context={"schema_urls": ["v1:schema-v1"]},
        ),
        name="swagger",
    ),
    path(
        "docs/oauth2-redirect",
        TemplateView.as_view(template_name="kanikervanaf/swagger-oauth2-redirect.html"),
        name="swagger-oauth-redirect",
    ),
]

website/kanikervanaf/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    IndexView,
    ContactView,
    FAQView,
    PrivacyPolicy,
    handler404 as custom_handler404,
    handler500 as custom_handler500,
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomeSitemap, ContactSitemap, FAQSitemap, PrivacySitemap
from posts.sitemaps import PostOverviewSitemap, PostCreateSitemap, PostDetailsSitemap
from subscriptions.sitemaps import (
    SubscriptionCategoryPageSitemap,
    SubscriptionListSitemap,
    SubscriptionDetailsSearchSitemap,
    SubscriptionDetailsSitemap,
    SubscriptionSummarySitemap,
    SubscriptionRequestSitemap,
    EnterUserSitemap,
)
from users.sitemaps import UserSitemap

sitemaps = {
    "home": HomeSitemap,
    "contact": ContactSitemap,
    "faq": FAQSitemap,
    "privacy": PrivacySitemap,
    "posts:post_create": PostCreateSitemap,
    "posts:post_overview": PostOverviewSitemap,
    "posts:details": PostDetailsSitemap,
    "subscriptions:overview": SubscriptionListSitemap,
    "subscriptions:overview_category_page": SubscriptionCategoryPageSitemap,
    "subscriptions:summary": SubscriptionSummarySitemap,
    "subscriptions:requets": SubscriptionRequestSitemap,
    "subscriptions:details_search": SubscriptionDetailsSearchSitemap,
    "subscriptions:details": SubscriptionDetailsSitemap,
    "subscriptions:enter": EnterUserSitemap,
    "users": UserSitemap,
}

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="home"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("faq", FAQView.as_view(), name="faq"),
    path("privacybeleid", PrivacyPolicy.as_view(), name="privacy"),
    path("contact", ContactView.as_view(), name="contact"),
    path("admin/", admin.site.urls),
    path(
        "subscriptions/",
        include(("subscriptions.urls", "subscriptions"), namespace="subscriptions"),
    ),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("api/", include("kanikervanaf.api.urls")),
]

website/posts/urls.py
from django.urls import path, register_converter
from .views import PostOverviewView, PostCreateView, PostDetailsView, PostUserOverview
from .converters import PostConverter

register_converter(PostConverter, "post")

urlpatterns = [
    path("overview/page/<int:page>", PostOverviewView.as_view(), name="post_overview"),
    path("create", PostCreateView.as_view(), name="post_create"),
    path(
        "details/<post:post>/page/<int:page>", PostDetailsView.as_view(), name="details"
    ),
    path(
        "messages/page/<int:page>",
        PostUserOverview.as_view(),
        name="post_user_overview",
    ),
]

website/subscriptions/api/v1/urls.py
from django.urls import path
from subscriptions.api.v1.views import (
    SubscriptionListAPIView,
    SubscriptionCategoryListAPIView,
    SubscriptionRetrieveAPIView,
    SubscriptionCategoryRetrieveAPIView,
    SubscriptionRenderLetterAPIView,
    SubscriptionRenderEmailAPIView,
    TemplateAPIView,
)


urlpatterns = [
    path("", SubscriptionListAPIView.as_view(), name="subscription_list"),
    path(
        "<int:pk>", SubscriptionRetrieveAPIView.as_view(), name="subscription_retrieve"
    ),
    path(
        "<int:pk>/render-letter",
        SubscriptionRenderLetterAPIView.as_view(),
        name="subscription_render_letter",
    ),
    path(
        "<int:pk>/render-email",
        SubscriptionRenderEmailAPIView.as_view(),
        name="subscription_render_email",
    ),
    path(
        "categories",
        SubscriptionCategoryListAPIView.as_view(),
        name="subscription_category_list",
    ),
    path(
        "categories/<int:pk>",
        SubscriptionCategoryRetrieveAPIView.as_view(),
        name="subscription_category_retrieve",
    ),
    path(
        "render-template",
        TemplateAPIView.as_view(),
        name="render_template",
    ),
]

website/subscriptions/urls.py
from django.urls import path, register_converter
from .views import (
    SubscriptionDetailsSearchView,
    SubscriptionDetailsView,
    SubscriptionDetailsRedirectView,
    SubscriptionListView,
    SummaryView,
    ListCategoryView,
    ListCategoryRedirectView,
    ListCategoryPageView,
    ListCategoryPageRedirectView,
    RequestView,
    verification_send,
    VerificationSendSucceeded,
    verify,
    VerificationSendFailed,
    AdminTemplateInformationView,
    BasicUserInformation,
)
from .converters import SubscriptionConverter, SubscriptionCategoryConverter

register_converter(SubscriptionConverter, "subscription")
register_converter(SubscriptionCategoryConverter, "category")

urlpatterns = [
    path(
        "",
        SubscriptionListView.as_view(),
        name="overview",
    ),
    path(
        "<category:category>",
        ListCategoryView.as_view(),
        name="overview_category",
    ),
    path(
        "<int:category>",
        ListCategoryRedirectView.as_view(),
        name="overview_category_redirect",
    ),
    path(
        "<category:category>/page/<int:page>",
        ListCategoryPageView.as_view(),
        name="overview_category_page",
    ),
    path(
        "<int:category>/page/<int:page>",
        ListCategoryPageRedirectView.as_view(),
        name="overview_category_page_redirect",
    ),
    path(
        "summary",
        SummaryView.as_view(),
        name="summary",
    ),
    path(
        "send",
        verification_send,
        name="send",
    ),
    path("request", RequestView.as_view(), name="request"),
    path("details", SubscriptionDetailsSearchView.as_view(), name="details_search"),
    path(
        "details/<subscription:subscription>",
        SubscriptionDetailsView.as_view(),
        name="details",
    ),
    path(
        "details/<int:subscription>",
        SubscriptionDetailsRedirectView.as_view(),
        name="details_redirect",
    ),
    path(
        "verify/<str:token>",
        verify,
        name="verify",
    ),
    path(
        "verification-request/succeeded",
        VerificationSendSucceeded.as_view(),
        name="verification_send_succeeded",
    ),
    path(
        "verification-request/failed",
        VerificationSendFailed.as_view(),
        name="verification_send_failed",
    ),
    path(
        "enter",
        BasicUserInformation.as_view(),
        name="enter",
    ),
    path(
        "admin/template-information",
        AdminTemplateInformationView.as_view(),
        name="admin_template_information",
    ),
]

website/subscriptions/api/v1/views.py
import datetime
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter

import django.template.exceptions
from rest_framework import status
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import IsAdminUser
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from kanikervanaf.api.openapi import CustomAutoSchema
from subscriptions.api.v1.pagination import StandardResultsSetPagination
from subscriptions.api.v1.renderers import (
    PDFRenderer,
    PlainTextRenderer,
    WordDocumentRenderer,
)
from subscriptions.api.v1.serializers import (
    SubscriptionSerializer,
    SubscriptionCategorySerializer,
)
from subscriptions.models import Subscription, SubscriptionCategory
from subscriptions.services import (
    render_deregister_letter_pdf,
    render_deregister_letter_docx,
    render_deregister_email,
    render_string,
    render_string_to_pdf,
)
from django.conf import settings


class SubscriptionListAPIView(ListAPIView):
    """
    Subscription List API View.

    Permissions required: None

    Use this endpoint to get a list of subscriptions in the database.
    """

    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.all()
    pagination_class = StandardResultsSetPagination
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category"]
    search_fields = ["name", "subscriptionsearchterm__name"]
    ordering_fields = ["name", "amount_used"]


class SubscriptionRetrieveAPIView(RetrieveAPIView):
    """
    Subscription Retrieve API View.

    Permission required: None

    Use this endpoint to get the details of a Subscription.
    """

    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.all()


class SubscriptionCategoryListAPIView(ListAPIView):
    """
    Subscription Category List API View.

    Permissions required: None

    Use this endpoint to get a list of subscription categories in the database.
    """

    serializer_class = SubscriptionCategorySerializer
    queryset = SubscriptionCategory.objects.all()
    pagination_class = StandardResultsSetPagination


class SubscriptionCategoryRetrieveAPIView(RetrieveAPIView):
    """
    Subscription Category Retrieve API View.

    Permission required: None

    Use this endpoint to get the details of a Subscription Category.
    """

    serializer_class = SubscriptionCategorySerializer
    queryset = SubscriptionCategory.objects.all()


class SubscriptionRenderLetterAPIView(APIView):
    """Subscription Render Letter API View."""

    schema = CustomAutoSchema(
        request_schema={
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "example": {
                        x: "string" for x in settings.DEFAULT_TEMPLATE_PARAMETERS
                    },
                },
            },
        }
    )

    renderer_classes = [WordDocumentRenderer, PDFRenderer]

    def post(self, request, **kwargs):
        """
        Render a letter to PDF or Word document.

        Permission required: None

        A context dictionary may be provided that includes context variables that can be passed to the template.
        """
        try:
            subscription = Subscription.objects.get(pk=kwargs.get("pk"))
        except Subscription.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        context = {}
        context.update(settings.DEFAULT_TEMPLATE_PARAMETERS)
        context.update(request.data.get("context", {}))
        if request.accepted_renderer.format == "pdf":
            pdf = render_deregister_letter_pdf(context, subscription)
            return Response(
                status=status.HTTP_200_OK, data=pdf, content_type="application/pdf"
            )
        else:
            docx = render_deregister_letter_docx(context, subscription)
            return Response(
                status=status.HTTP_200_OK,
                data=docx,
                content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )


class SubscriptionRenderEmailAPIView(APIView):
    """
    Subscription Render Email API View.

    Permission required: None

    Use this endpoint to render the email of a Subscription.
    """

    schema = CustomAutoSchema(
        request_schema={
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "example": {
                        x: "string" for x in settings.DEFAULT_TEMPLATE_PARAMETERS
                    },
                },
            },
        }
    )

    renderer_classes = [PlainTextRenderer]

    def post(self, request, **kwargs):
        """Get request."""
        try:
            instance = Subscription.objects.get(pk=kwargs.get("pk"))
        except Subscription.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        context = {}
        context.update(settings.DEFAULT_TEMPLATE_PARAMETERS)
        context.update(request.data.get("context", {}))
        email = render_deregister_email(
            context,
            instance,
        )
        return Response(
            status=status.HTTP_200_OK, data=email, content_type="text/plain"
        )


class TemplateAPIView(APIView):
    """
    Template API View.

    Permission required: is_staff

    Use this endpoint to render a user submitted template with a user submitted context.
    """

    schema = CustomAutoSchema(
        request_schema={
            "type": "object",
            "properties": {
                "source": {"type": "string", "example": "string"},
                "context": {"type": "object", "example": {"name": "string"}},
            },
        }
    )

    renderer_classes = [WordDocumentRenderer, PDFRenderer, PlainTextRenderer]
    permission_classes = [IsAdminUser]

    def post(self, request, **kwargs):
        """Render user submitted template."""
        if "source" not in request.data.keys() or "context" not in request.data.keys():
            return Response(status=status.HTTP_400_BAD_REQUEST)
        context_data = {
            "date": datetime.datetime.now().strftime("%d-%m-%Y"),
        }
        context_data.update(request.data["context"])
        if request.accepted_renderer.format == "pdf":
            try:
                pdf = render_string_to_pdf(request.data["source"], context_data)
            except (
                django.template.exceptions.TemplateSyntaxError,
                django.template.exceptions.TemplateDoesNotExist,
            ) as e:
                request.accepted_renderer = JSONRenderer()
                return Response(
                    status=status.HTTP_400_BAD_REQUEST,
                    data={"detail": e.__str__()},
                    content_type="application/json",
                )
            return Response(
                status=status.HTTP_200_OK, data=pdf, content_type="application/pdf"
            )
        else:
            try:
                text = render_string(request.data["source"], context_data)
            except (
                django.template.exceptions.TemplateSyntaxError,
                django.template.exceptions.TemplateDoesNotExist,
            ) as e:
                request.accepted_renderer = JSONRenderer()
                return Response(
                    status=status.HTTP_400_BAD_REQUEST,
                    data={"detail": e.__str__()},
                    content_type="application/json",
                )
            return Response(
                status=status.HTTP_200_OK, data=text, content_type="text/plain"
            )

website/subscriptions/templates/subscriptions/admin/template_editor.html
{% extends 'admin/change_form.html' %}
{% load i18n admin_urls static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'subscriptions/admin/codemirror/codemirror.css' %}">
    <link href="{% static "subscriptions/admin/css/template-editor.css" %}" rel="stylesheet">
{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
            &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
            &rsaquo; {% if has_view_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
            &rsaquo; <a href="{% url opts|admin_urlname:'change' original.id %}">{{ original|truncatewords:"18" }}</a>
            &rsaquo; {{ view_name }}
        </div>
    {% endblock %}
{% endif %}

{% block content %}
    <div id="vue-template-container">
        {% if saved or error %}
            <ul class="messagelist">
                {% if saved %}
                    <li class="succes">File saved successfully.</li>
                {% endif %}
                {% if error %}
                    <p class="error">An error occurred while saving the template, please contact an administrator.</p>
                {% endif %}
            </ul>
        {% endif %}
        <h1>{{ view_name }}</h1>
        <ul class="object-tools">
            <li>
                <a href="{% url 'subscriptions:admin_template_information' %}">Template information</a>
            </li>
        </ul>
        <div class="template-editor-container">
            <h2>Template editor</h2>
            <label for="template-editor"></label>
            <form ref="form" method="POST">
                {% csrf_token %}
                <textarea ref="original_editor" id="template-editor" name="source">{{ saved_template }}</textarea>
            </form>
            <div class="button button-disabled" v-if="loading_pdf">Opslaan <span class="loader"></span></div>
            <input v-else type="button" value="Opslaan" v-on:click="save"/>

            <div class="button button-disabled" v-if="loading_pdf">Maak voorbeeld <span class="loader"></span></div>
            <input v-else type="button" value="Maak voorbeeld" v-on:click="render_pdf"/>
        </div>
        <div id="template-container">
            <div class="template-editor-left">
                <div class="template-form-container">
                    <h2>Gegevens</h2>
                    <form class="template-form">
                        <label for="firstname">Voornaam</label>
                        <input v-model="template_data.firstname" type="text" id="firstname">
                        <label for="lastname">Achternaam</label>
                        <input v-model="template_data.lastname" type="text" id="lastname">
                        <label for="email_address">E-mail adres</label>
                        <input v-model="template_data.email_address" type="text" id="email_address">
                        <label for="address">Adres</label>
                        <input v-model="template_data.address" type="text" id="address">
                        <label for="postal_code">Postcode</label>
                        <input v-model="template_data.postal_code" type="text" id="postal_code">
                        <label for="residence">Woonplaats</label>
                        <input v-model="template_data.residence" type="text" id="residence">
                        <label for="residence">Abonnement naam</label>
                        <input v-model="template_data.subscription_name" type="text" id="residence">
                        <label for="residence">Abonnement adres</label>
                        <input v-model="template_data.subscription_address" type="text" id="residence">
                        <label for="residence">Abonnement postcode</label>
                        <input v-model="template_data.subscription_postal_code" type="text" id="residence">
                        <label for="residence">Abonnement plaats</label>
                        <input v-model="template_data.subscription_residence" type="text" id="residence">
                    </form>
                </div>
            </div>
            <div class="template-editor-right">
                <div class="preview">
                    <h2>Voorbeeld</h2>
                    <iframe v-if="pdf !== null" :src="pdf" class="preview-frame"></iframe>
                    <p v-if="error !== null" class="errornote"><% error %></p>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
    <script type="text/javascript" src="{% static "subscriptions/admin/codemirror/codemirror.js" %}"></script>
    <script type="text/javascript" src="{% static "subscriptions/admin/codemirror/addon/mode/overlay.js" %}"></script>
    <script type="text/javascript" src="{% static "subscriptions/admin/codemirror/mode/xml/xml.js" %}"></script>
    <script type="text/javascript" src="{% static "subscriptions/admin/codemirror/mode/htmlmixed/htmlmixed.js" %}"></script>
    <script type="text/javascript" src="{% static "subscriptions/admin/codemirror/mode/django/django.js" %}"></script>
    <script>
        let template_vue = new Vue({
            el: '#vue-template-container',
            delimiters: ['<%', '%>'],
            data: {
                template_data: {
                    firstname: "John",
                    lastname: "Doe",
                    email_address: "johndoe@email.com",
                    address: "Heyendaalseweg 135",
                    postal_code: "6525 AJ",
                    residence: "Nijmegen",
                    subscription_name: "{% autoescape on %}{{ instance_name }}{% endautoescape %}",
                    subscription_address: "{% autoescape on %}{{ instance_address }}{% endautoescape %}",
                    subscription_postal_code: "{% autoescape on %}{{ instance_postal_code }}{% endautoescape %}",
                    subscription_residence: "{% autoescape on %}{{ instance_city }}{% endautoescape %}",
                },
                editor: null,
                pdf: null,
                loading_pdf: false,
                error: null,
            },
            methods: {
                save: function() {
                    this.loading_pdf = true;
                    this.$refs.original_editor.value = this.editor.getValue();
                    if (confirm("Wil je opslaan?")) {
                        this.$refs.form.submit();
                    }
                    this.loading_pdf = false;
                },
                render_pdf: function () {
                    this.loading_pdf = true;
                    let source = this.editor.getValue();
                    fetch("{% url 'v1:render_template' %}",
                    {
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': "{{ csrf_token }}",
                            'Accept': "{{ accepts }}"
                        },
                        method: "POST",
                        body: JSON.stringify({
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                            source: source,
                            context: this.template_data
                        })
                    })
                    .then(
                        async function(res)
                        {
                            template_vue.loading_pdf = false;
                            if (res.status !== 200) {
                                template_vue.pdf = null;
                                res.json().then(json => {
                                    if (json.detail) {
                                        template_vue.error = `Template rendering failed with status code ${res.status}: ${json.detail}`;
                                    }
                                    else {
                                        template_vue.error = `Template rendering failed with status code ${res.status}`;
                                    }
                                });
                            }
                            else {
                                template_vue.pdf = window.URL.createObjectURL(await res.blob());
                                template_vue.error = null;
                            }
                        })
                    .catch(
                        function(res)
                        {
                            template_vue.loading_pdf = false;
                            template_vue.pdf = null;
                            template_vue.error = `Template rendering failed with status code ${res.status}`;
                        })
                }
            },
            mounted() {
                this.editor = CodeMirror.fromTextArea(document.getElementById("template-editor"), {
                    mode: "django",
                    indentUnit: 2,
                    indentWithTabs: true,
                    lineNumbers: true,
                    lineWrapping: true,
                });
                this.render_pdf();
            }
        });
    </script>
{% endblock %}