website/kanikervanaf/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "",
        include(
            [
                path("v1/", include("kanikervanaf.api.v1.urls", namespace="v1")),
            ]
        ),
    ),  # noqa
    path(
        "docs",
        TemplateView.as_view(
            template_name="kanikervanaf/swagger.html",
            extra_context={"schema_urls": ["v1:schema-v1"]},
        ),
        name="swagger",
    ),
    path(
        "docs/oauth2-redirect",
        TemplateView.as_view(template_name="kanikervanaf/swagger-oauth2-redirect.html"),
        name="swagger-oauth-redirect",
    ),
]

website/kanikervanaf/api/v1/urls.py
from django.urls import path, include
from rest_framework.schemas import get_schema_view

from kanikervanaf.api.openapi import OpenAPISchemaGenerator

app_name = "kanikervanaf"

urlpatterns = [
    path("subscriptions/", include("subscriptions.api.v1.urls")),
    path("posts/", include("posts.api.v1.urls")),
    path(
        "schema",
        get_schema_view(
            title="API v1",
            url="/api/v1/",
            version=1,
            urlconf="kanikervanaf.api.v1.urls",
            generator_class=OpenAPISchemaGenerator,
        ),
        name="schema-v1",
    ),
]

website/kanikervanaf/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    IndexView,
    ContactView,
    FAQView,
    PrivacyPolicy,
    handler404 as custom_handler404,
    handler500 as custom_handler500,
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomeSitemap, ContactSitemap, FAQSitemap, PrivacySitemap
from posts.sitemaps import PostOverviewSitemap, PostCreateSitemap, PostDetailsSitemap
from subscriptions.sitemaps import (
    SubscriptionCategoryPageSitemap,
    SubscriptionListSitemap,
    SubscriptionDetailsSearchSitemap,
    SubscriptionDetailsSitemap,
    SubscriptionSummarySitemap,
    SubscriptionRequestSitemap,
    EnterUserSitemap,
)
from users.sitemaps import UserSitemap

sitemaps = {
    "home": HomeSitemap,
    "contact": ContactSitemap,
    "faq": FAQSitemap,
    "privacy": PrivacySitemap,
    "posts:post_create": PostCreateSitemap,
    "posts:post_overview": PostOverviewSitemap,
    "posts:details": PostDetailsSitemap,
    "subscriptions:overview": SubscriptionListSitemap,
    "subscriptions:overview_category_page": SubscriptionCategoryPageSitemap,
    "subscriptions:summary": SubscriptionSummarySitemap,
    "subscriptions:requets": SubscriptionRequestSitemap,
    "subscriptions:details_search": SubscriptionDetailsSearchSitemap,
    "subscriptions:details": SubscriptionDetailsSitemap,
    "subscriptions:enter": EnterUserSitemap,
    "users": UserSitemap,
}

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="home"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("faq", FAQView.as_view(), name="faq"),
    path("privacybeleid", PrivacyPolicy.as_view(), name="privacy"),
    path("contact", ContactView.as_view(), name="contact"),
    path("admin/", admin.site.urls),
    path(
        "subscriptions/",
        include(("subscriptions.urls", "subscriptions"), namespace="subscriptions"),
    ),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("api/", include("kanikervanaf.api.urls")),
]

website/posts/urls.py
from django.urls import path, register_converter
from .views import PostOverviewView, PostCreateView, PostDetailsView, PostUserOverview
from .converters import PostConverter

register_converter(PostConverter, "post")

urlpatterns = [
    path("overview/page/<int:page>", PostOverviewView.as_view(), name="post_overview"),
    path("create", PostCreateView.as_view(), name="post_create"),
    path(
        "details/<post:post>/page/<int:page>", PostDetailsView.as_view(), name="details"
    ),
    path(
        "messages/page/<int:page>",
        PostUserOverview.as_view(),
        name="post_user_overview",
    ),
]

website/subscriptions/urls.py
from django.urls import path, register_converter
from .views import (
    SubscriptionDetailsSearchView,
    SubscriptionDetailsView,
    SubscriptionDetailsRedirectView,
    SubscriptionListView,
    SummaryView,
    ListCategoryView,
    ListCategoryRedirectView,
    ListCategoryPageView,
    ListCategoryPageRedirectView,
    RequestView,
    verification_send,
    VerificationSendSucceeded,
    verify,
    VerificationSendFailed,
    AdminTemplateInformationView,
    BasicUserInformation,
)
from .converters import SubscriptionConverter, SubscriptionCategoryConverter

register_converter(SubscriptionConverter, "subscription")
register_converter(SubscriptionCategoryConverter, "category")

urlpatterns = [
    path(
        "",
        SubscriptionListView.as_view(),
        name="overview",
    ),
    path(
        "<category:category>",
        ListCategoryView.as_view(),
        name="overview_category",
    ),
    path(
        "<int:category>",
        ListCategoryRedirectView.as_view(),
        name="overview_category_redirect",
    ),
    path(
        "<category:category>/page/<int:page>",
        ListCategoryPageView.as_view(),
        name="overview_category_page",
    ),
    path(
        "<int:category>/page/<int:page>",
        ListCategoryPageRedirectView.as_view(),
        name="overview_category_page_redirect",
    ),
    path(
        "summary",
        SummaryView.as_view(),
        name="summary",
    ),
    path(
        "send",
        verification_send,
        name="send",
    ),
    path("request", RequestView.as_view(), name="request"),
    path("details", SubscriptionDetailsSearchView.as_view(), name="details_search"),
    path(
        "details/<subscription:subscription>",
        SubscriptionDetailsView.as_view(),
        name="details",
    ),
    path(
        "details/<int:subscription>",
        SubscriptionDetailsRedirectView.as_view(),
        name="details_redirect",
    ),
    path(
        "verify/<str:token>",
        verify,
        name="verify",
    ),
    path(
        "verification-request/succeeded",
        VerificationSendSucceeded.as_view(),
        name="verification_send_succeeded",
    ),
    path(
        "verification-request/failed",
        VerificationSendFailed.as_view(),
        name="verification_send_failed",
    ),
    path(
        "enter",
        BasicUserInformation.as_view(),
        name="enter",
    ),
    path(
        "admin/template-information",
        AdminTemplateInformationView.as_view(),
        name="admin_template_information",
    ),
]

website/users/urls.py
from django.urls import path
from .views import (
    LoginView,
    RegisterView,
    ForgotView,
    LogoutView,
    ResetView,
    AccountView,
    EmailConfirmView,
)

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", RegisterView.as_view(), name="register"),
    path("forgot", ForgotView.as_view(), name="forgot"),
    path("reset/<str:token>", ResetView.as_view(), name="reset"),
    path("update/<str:token>", EmailConfirmView.as_view(), name="confirm"),
    path("account", AccountView.as_view(), name="account"),
]

website/kanikervanaf/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from django.conf import settings


class ContactForm(forms.Form):
    """Contact form."""

    name = forms.CharField(label="Naam")
    title = forms.CharField(label="Titel")
    email = forms.EmailField(label="Email adres")
    content = forms.CharField(
        widget=forms.TextInput(attrs={"id": "contact_content"}),
        label="Bericht",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        """Only load captcha on production."""
        super().__init__(*args, **kwargs)
        if settings.RECAPTCHA_PUBLIC_KEY != "" and settings.RECAPTCHA_PRIVATE_KEY != "":
            self.fields["captcha"] = ReCaptchaField(
                widget=ReCaptchaV3(api_params={"hl": "nl"}), label=""
            )

website/kanikervanaf/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .services import send_contact_email
from .forms import ContactForm


class IndexView(TemplateView):
    """Home view."""

    template_name = "kanikervanaf/index.html"


class FAQView(TemplateView):
    """Frequently asked questions view."""

    template_name = "kanikervanaf/faq.html"


class PrivacyPolicy(TemplateView):
    """Frequently asked questions view."""

    template_name = "kanikervanaf/privacy.html"


class ContactView(TemplateView):
    """Contact view."""

    template_name = "kanikervanaf/contact.html"

    def get(self, request, **kwargs):
        """
        GET request function for request view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: the contact.html page
        """
        initial = {
            "name": request.user.get_full_name()
            if request.user.is_authenticated
            else None,
            "email": request.user.email if request.user.is_authenticated else None,
        }
        form = ContactForm(initial=initial)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        POST request function for the request view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the contact.html page, either with a succeeded or failed message indicating if the request
        was send successfully or not
        """
        form = ContactForm(request.POST)
        context = {"form": form}
        if form.is_valid():
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            title = form.cleaned_data.get("title")
            message = form.cleaned_data.get("content")
            context["form"] = ContactForm(None)
            if send_contact_email(name, email, title, message):
                context["succeeded"] = True
                return render(request, self.template_name, context)
            else:
                context["failed"] = True
                return render(request, self.template_name, context)
        else:
            return render(request, self.template_name, context)


def handler404(request, exception):
    """
    Handle a 404 (page not found) exception.

    :param request: the request
    :param exception: the exception
    :return: a render of the 404 page
    """
    return render(request, "kanikervanaf/404.html", status=404)


def handler500(request):
    """
    Handle a 50x (server fault) exception.

    :param request: the request
    :return: a render of the 500 page
    """
    return render(request, "kanikervanaf/500.html", status=500)

website/kanikervanaf/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}Kanikervanaf{% endblock %}
    </title>
    {% include 'analytics.html' %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'kanikervanaf/img/favicon.ico' %}"/>
    <link rel="icon" type="image/x-icon" href="{% static 'kanikervanaf/img/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'kanikervanaf/css/bootstrap.css' %}"/>
    {% block styles %}{% endblock %}
    <link rel="icon" href="{% static "kanikervanaf/img/browser/icon.jpg" %}">
    <link rel="apple-touch-icon" href="{% static "kanikervanaf/img/browser/apple-touch-icon.jpg" %}">
    <meta name="msapplication-square32x32logo"
          content="{% static "kanikervanaf/img/browser/icon-smalltile.jpg" %}">
    <meta name="msapplication-square150x150logo"
          content="{% static "kanikervanaf/img/browser/icon-mediumtile.jpg" %}">
    <meta name="msapplication-wide272x182logo"
          content="{% static "kanikervanaf/img/browser/icon-widetile.jpg" %}">
    <meta name="msapplication-square300x300logo"
          content="{% static "kanikervanaf/img/browser/icon-largetile.jpg" %}">
    <meta name="keywords" content="Opzeggen, Abonnementen, Abonnement, Gratis">
    <meta name="description" content="{% block page_description %}Snel en gratis automatisch abonnementen opzeggen. Aanklikken, gegevens invoeren en versturen!{% endblock %}">
    <script src="https://kit.fontawesome.com/4e8cabe8e2.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/sx4eugpieda3a9a2mjzq9xh0ht6h59prb6wgd8gd3yqcjif5/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "home" %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Home
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url "home" %}">Home</a>
                        <a class="dropdown-item" href="{% url "subscriptions:details_search" %}">Contactgegevens opzoeken</a>
                        <a class="dropdown-item" href="{% url "posts:post_overview" page=1 %}">Berichten</a>
                        <a class="dropdown-item" href="{% url "contact" %}">Contact</a>
                        <a class="dropdown-item" href="{% url "faq" %}">FAQ</a>
                        <a class="dropdown-item" href="{% url "subscriptions:request" %}">Vraag abonnement aan</a>
                    </div>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarAccountMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if user.is_authenticated %}
                            Mijn account
                        {% else %}
                            Account
                        {% endif %}
                    </a>
                    {% if user.is_authenticated %}
                        <div class="dropdown-menu" aria-labelledby="navbarAccountMenuLink">
                            <a class="dropdown-item" href="{% url "users:account" %}">Overzicht</a>
                            <a class="dropdown-item" href="{% url "users:logout" %}">Uitloggen</a>
                        </div>
                    {% else %}
                        <div class="dropdown-menu" aria-labelledby="navbarAccountMenuLink">
                            <a class="dropdown-item" href="{% url "users:login" %}">Log in</a>
                            <a class="dropdown-item" href="{% url "users:forgot" %}">Wachtwoord vergeten</a>
                        </div>
                    {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "subscriptions:overview" %}">1. Selecteer abonnementen</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "users:enter" %}">2. Voer uw gegevens in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "subscriptions:summary" %}">3. Versturen</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block page %}{% endblock %}
    {% block footer %}
        <footer class="page-footer font-small pt-4">
            <div class="footer-copyright text-center py-3">© 2020 Copyright:
                <a href="/">kanikervanaf.nl</a>
            </div>
        </footer>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
        CSRF_TOKEN = "{{ csrf_token }}";
    </script>
    {%  block js %}{%  endblock %}
</body>
</html>

website/kanikervanaf/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Kanikervanaf: Contact
{% endblock %}

{% block page_description %}
    Neem contact met ons op via onze contactgegevens of het formulier op deze pagina.
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'kanikervanaf/css/fluid-input.css' %}"/>
{% endblock %}

{% block page %}
<div class="container">
    {% if succeeded %}
        <p class="container-fluid message-ok">Uw contactbericht is verzonden!</p>
    {% elif failed %}
        <p class="container-fluid message-error">Er is iets misgegaan met het verzenden van uw contactbericht.</p>
    {% endif %}
    <h1>Contact</h1>
    <p>Heeft u vragen voor ons? Kloppen onze gegevens niet? Stel uw vraag in het feedback formulier hieronder! U kunt
        ook zelf een mail sturen naar klantenservice@kanikervanaf.nl.</p>
    <p>Wilt u een abonnement wat u mist aanvragen zodat wij het op onze site kunnen zetten, doe dit dan
        <a href="{% url "subscriptions:request" %}">hier</a>.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary mt-3" type="submit" value="Verzenden"/>
    </form>
</div>
{% endblock %}
{% block js %}
    <script>
        tinymce.init({
            selector: '#contact_content'
        });
    </script>
{% endblock %}

website/kanikervanaf/templates/faq.html
{% extends 'base.html' %}

{% block title %}
    Kanikervanaf: FAQ
{% endblock %}

{% block page_description %}
    Bekijk alle veelgestelde vragen over kanikervanaf.nl.
{% endblock %}

{% block page %}
    <div class="container">
        <h1>Frequently asked questions</h1>

        <h3>Wat is kanikervanaf.nl?</h3>

        <p>Kanikervanaf.nl is een website waar u uw abonnementen handig in één keer op kunt zeggen. U hoeft slechts de
            abonnementen te selecteren en wij doen de rest.</p>

        <h3>Is kanikervanaf.nl gratis?</h3>

        <p>Kanikervanaf.nl is volledig gratis!</p>

        <h3>Het bedrijf wat ik wil opzeggen staat niet in de lijst, wat nu?</h3>

        <p>Onze database is blijkbaar nog niet compleet! U kunt ons helpen deze uit te breiden door ons te mailen op
            info@kanikervanaf.nl met het bedrijf in kwestie.</p>

        <h3>Hoe werkt het opzeggen?</h3>

        <p>Opzeggen kan heel eenvoudig in drie stappen: u selecteert de bedrijven waarvan u de abonnementen wilt opzeggen,
            u vult uw persoonlijke gegevens in en daarna hoeft u zich alleen nog maar te verifiëren via onze
            verificatiemail.</p>

        <h3>Welke gegevens moet ik invullen?</h3>

        <p>De enige verplichte gegevens zijn uw mailadres en voornaam, maar hoe meer gegevens wij aan het bedrijf kunnen
            geven, hoe gemakkelijker het opzeggen zal verlopen. U kunt zelf kiezen welke gegevens u met ons deelt in stap
            twee.</p>

        <h3>Wat doen wij met uw gegevens?</h3>

        <p>Wij gebruiken uw gegevens om de opzegmails te maken. Uw gegevens worden verwijderd nadat uw opzegmails verzonden
            zijn.</p>
    </div>
{% endblock %}

website/kanikervanaf/templates/privacy.html
{% extends 'base.html' %}

{% block title %}
    Kanikervanaf: Privacy beleid
{% endblock %}

{% block page_description %}
    Bekijk ons privacybeleid en neem waar nodig contact met ons op.
{% endblock %}

{% block page %}
    <div class="container">
        <h1>Privacy beleid</h1>
        <h2>Wie zijn we?</h2>

        <p>Kanikervanaf.nl is een gratis tool ontwikkeld door Prikkl B.V. De tool is echter gratis te gebruiken voor
            iedereen die dat wil!</p>
        <h2>Welke persoonlijke gegevens verzamelen we en waarom verzamelen we die?</h2>

        <h3>Cookies</h3>
        <p>Wanneer je je gegevens invult op onze site, zullen die gegevens voor maximaal één dag worden opgeslagen op
            je eigen computer. Pas als je klaar bent met alles invullen en op 'versturen' drukt om de opzegmails te
            versturen, worden jouw gegevens naar onze server gestuurd om verwerkt te worden. Dit is nodig omdat wij de
            e-mails voor jou versturen.</p>
        <p>Zodra je jouw e-mailadres hebt geverifieerd en de opzegmails definitief verstuurd zijn, verwijderen we jouw
            gegevens. Mocht je je e-mailadres niet verifiëren, dan worden jouw gegevens na 15 minuten weer verwijderd
            van onze server.</p>
        <p>Om het gebruik van de site te monitoren, maken wij ook gebruik van Google Analytics. Google Analytics plaatst
            ook een cookie op uw computer om uw bezoek te traceren, zodat wij onze functionaliteit kunnen optimaliseren.
            Google Analytics ontvangt geen persoonlijke gegevens die je invult! Je ip-adres wordt geanonimiseerd en de
            gegevens die je op onze website invult worden niet verstuurd naar Google. De anonieme gegevens die Google
            verzamelt worden maximaal 3 jaar bewaard. </p>

        <h2>Hoe lang we jouw data bewaren</h2>
        <p>De data die u op onze site invoert wordt in principe een dag op uw computer opgeslagen. Indien u op versturen
            drukt zullen deze gegevens naar onze servers worden verzonden en worden ze op onze server opgeslagen. Deze
            gegevens blijven een kwartier geldig. Als u uw mailadres heeft geverifieerd door op verifiëren te drukken
            in de verificatiemail worden uw gegevens direct van onze server verwijderd.</p>

        <h2>Account</h2>
        <p>
            Bovenstaande geldt niet als jij een account op de website hebt aangemaakt. Indien jij een account hebt
            aangemaakt worden je gebruikersnaam en e-mail adres op onze server opgeslagen.
        </p>

        <h2>Welke rechten je hebt over je data</h2>
        <p>Uiteraard kun je altijd ons verzoeken alle persoonlijke gegevens die we van je hebben te verwijderen of in
            te zien. Dit bevat geen gegevens die we verplicht moeten bewaren in verband met administratieve, wettelijke
            of beveiligingsdoeleinden.</p>

        <h2>Contactinformatie</h2>
        <p>Je kunt ons benaderen via klantenservice@kanikervanaf.nl</p>

    </div>
{% endblock %}

website/kanikervanaf/templates/sidebar.html
{% extends 'base.html' %}
{% block page %}
    <div class="container-xl mt-5">
        <div class="row">
            <div class="col-md">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4">
                {% block sidebar %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}