website/kanikervanaf/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "",
        include(
            [
                path("v1/", include("kanikervanaf.api.v1.urls", namespace="v1")),
            ]
        ),
    ),  # noqa
    path(
        "docs",
        TemplateView.as_view(
            template_name="kanikervanaf/swagger.html",
            extra_context={"schema_urls": ["v1:schema-v1"]},
        ),
        name="swagger",
    ),
    path(
        "docs/oauth2-redirect",
        TemplateView.as_view(template_name="kanikervanaf/swagger-oauth2-redirect.html"),
        name="swagger-oauth-redirect",
    ),
]

website/kanikervanaf/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    IndexView,
    ContactView,
    FAQView,
    PrivacyPolicy,
    handler404 as custom_handler404,
    handler500 as custom_handler500,
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomeSitemap, ContactSitemap, FAQSitemap, PrivacySitemap
from posts.sitemaps import PostOverviewSitemap, PostCreateSitemap, PostDetailsSitemap
from subscriptions.sitemaps import (
    SubscriptionCategoryPageSitemap,
    SubscriptionListSitemap,
    SubscriptionDetailsSearchSitemap,
    SubscriptionDetailsSitemap,
    SubscriptionSummarySitemap,
    SubscriptionRequestSitemap,
    EnterUserSitemap,
)
from users.sitemaps import UserSitemap

sitemaps = {
    "home": HomeSitemap,
    "contact": ContactSitemap,
    "faq": FAQSitemap,
    "privacy": PrivacySitemap,
    "posts:post_create": PostCreateSitemap,
    "posts:post_overview": PostOverviewSitemap,
    "posts:details": PostDetailsSitemap,
    "subscriptions:overview": SubscriptionListSitemap,
    "subscriptions:overview_category_page": SubscriptionCategoryPageSitemap,
    "subscriptions:summary": SubscriptionSummarySitemap,
    "subscriptions:requets": SubscriptionRequestSitemap,
    "subscriptions:details_search": SubscriptionDetailsSearchSitemap,
    "subscriptions:details": SubscriptionDetailsSitemap,
    "subscriptions:enter": EnterUserSitemap,
    "users": UserSitemap,
}

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="home"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("faq", FAQView.as_view(), name="faq"),
    path("privacybeleid", PrivacyPolicy.as_view(), name="privacy"),
    path("contact", ContactView.as_view(), name="contact"),
    path("admin/", admin.site.urls),
    path(
        "subscriptions/",
        include(("subscriptions.urls", "subscriptions"), namespace="subscriptions"),
    ),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("api/", include("kanikervanaf.api.urls")),
]

website/posts/urls.py
from django.urls import path, register_converter
from .views import PostOverviewView, PostCreateView, PostDetailsView, PostUserOverview
from .converters import PostConverter

register_converter(PostConverter, "post")

urlpatterns = [
    path("overview/page/<int:page>", PostOverviewView.as_view(), name="post_overview"),
    path("create", PostCreateView.as_view(), name="post_create"),
    path(
        "details/<post:post>/page/<int:page>", PostDetailsView.as_view(), name="details"
    ),
    path(
        "messages/page/<int:page>",
        PostUserOverview.as_view(),
        name="post_user_overview",
    ),
]

website/subscriptions/api/v1/urls.py
from django.urls import path
from subscriptions.api.v1.views import (
    SubscriptionListAPIView,
    SubscriptionCategoryListAPIView,
    SubscriptionRetrieveAPIView,
    SubscriptionCategoryRetrieveAPIView,
    SubscriptionRenderLetterAPIView,
    SubscriptionRenderEmailAPIView,
    TemplateAPIView,
)


urlpatterns = [
    path("", SubscriptionListAPIView.as_view(), name="subscription_list"),
    path(
        "<int:pk>", SubscriptionRetrieveAPIView.as_view(), name="subscription_retrieve"
    ),
    path(
        "<int:pk>/render-letter",
        SubscriptionRenderLetterAPIView.as_view(),
        name="subscription_render_letter",
    ),
    path(
        "<int:pk>/render-email",
        SubscriptionRenderEmailAPIView.as_view(),
        name="subscription_render_email",
    ),
    path(
        "categories",
        SubscriptionCategoryListAPIView.as_view(),
        name="subscription_category_list",
    ),
    path(
        "categories/<int:pk>",
        SubscriptionCategoryRetrieveAPIView.as_view(),
        name="subscription_category_retrieve",
    ),
    path(
        "render-template",
        TemplateAPIView.as_view(),
        name="render_template",
    ),
]

website/subscriptions/urls.py
from django.urls import path, register_converter
from .views import (
    SubscriptionDetailsSearchView,
    SubscriptionDetailsView,
    SubscriptionDetailsRedirectView,
    SubscriptionListView,
    SummaryView,
    ListCategoryView,
    ListCategoryRedirectView,
    ListCategoryPageView,
    ListCategoryPageRedirectView,
    RequestView,
    verification_send,
    VerificationSendSucceeded,
    verify,
    VerificationSendFailed,
    AdminTemplateInformationView,
    BasicUserInformation,
)
from .converters import SubscriptionConverter, SubscriptionCategoryConverter

register_converter(SubscriptionConverter, "subscription")
register_converter(SubscriptionCategoryConverter, "category")

urlpatterns = [
    path(
        "",
        SubscriptionListView.as_view(),
        name="overview",
    ),
    path(
        "<category:category>",
        ListCategoryView.as_view(),
        name="overview_category",
    ),
    path(
        "<int:category>",
        ListCategoryRedirectView.as_view(),
        name="overview_category_redirect",
    ),
    path(
        "<category:category>/page/<int:page>",
        ListCategoryPageView.as_view(),
        name="overview_category_page",
    ),
    path(
        "<int:category>/page/<int:page>",
        ListCategoryPageRedirectView.as_view(),
        name="overview_category_page_redirect",
    ),
    path(
        "summary",
        SummaryView.as_view(),
        name="summary",
    ),
    path(
        "send",
        verification_send,
        name="send",
    ),
    path("request", RequestView.as_view(), name="request"),
    path("details", SubscriptionDetailsSearchView.as_view(), name="details_search"),
    path(
        "details/<subscription:subscription>",
        SubscriptionDetailsView.as_view(),
        name="details",
    ),
    path(
        "details/<int:subscription>",
        SubscriptionDetailsRedirectView.as_view(),
        name="details_redirect",
    ),
    path(
        "verify/<str:token>",
        verify,
        name="verify",
    ),
    path(
        "verification-request/succeeded",
        VerificationSendSucceeded.as_view(),
        name="verification_send_succeeded",
    ),
    path(
        "verification-request/failed",
        VerificationSendFailed.as_view(),
        name="verification_send_failed",
    ),
    path(
        "enter",
        BasicUserInformation.as_view(),
        name="enter",
    ),
    path(
        "admin/template-information",
        AdminTemplateInformationView.as_view(),
        name="admin_template_information",
    ),
]

website/subscriptions/api/v1/views.py
import datetime
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter

import django.template.exceptions
from rest_framework import status
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import IsAdminUser
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from kanikervanaf.api.openapi import CustomAutoSchema
from subscriptions.api.v1.pagination import StandardResultsSetPagination
from subscriptions.api.v1.renderers import (
    PDFRenderer,
    PlainTextRenderer,
    WordDocumentRenderer,
)
from subscriptions.api.v1.serializers import (
    SubscriptionSerializer,
    SubscriptionCategorySerializer,
)
from subscriptions.models import Subscription, SubscriptionCategory
from subscriptions.services import (
    render_deregister_letter_pdf,
    render_deregister_letter_docx,
    render_deregister_email,
    render_string,
    render_string_to_pdf,
)
from django.conf import settings


class SubscriptionListAPIView(ListAPIView):
    """
    Subscription List API View.

    Permissions required: None

    Use this endpoint to get a list of subscriptions in the database.
    """

    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.all()
    pagination_class = StandardResultsSetPagination
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category"]
    search_fields = ["name", "subscriptionsearchterm__name"]
    ordering_fields = ["name", "amount_used"]


class SubscriptionRetrieveAPIView(RetrieveAPIView):
    """
    Subscription Retrieve API View.

    Permission required: None

    Use this endpoint to get the details of a Subscription.
    """

    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.all()


class SubscriptionCategoryListAPIView(ListAPIView):
    """
    Subscription Category List API View.

    Permissions required: None

    Use this endpoint to get a list of subscription categories in the database.
    """

    serializer_class = SubscriptionCategorySerializer
    queryset = SubscriptionCategory.objects.all()
    pagination_class = StandardResultsSetPagination


class SubscriptionCategoryRetrieveAPIView(RetrieveAPIView):
    """
    Subscription Category Retrieve API View.

    Permission required: None

    Use this endpoint to get the details of a Subscription Category.
    """

    serializer_class = SubscriptionCategorySerializer
    queryset = SubscriptionCategory.objects.all()


class SubscriptionRenderLetterAPIView(APIView):
    """Subscription Render Letter API View."""

    schema = CustomAutoSchema(
        request_schema={
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "example": {
                        x: "string" for x in settings.DEFAULT_TEMPLATE_PARAMETERS
                    },
                },
            },
        }
    )

    renderer_classes = [WordDocumentRenderer, PDFRenderer]

    def post(self, request, **kwargs):
        """
        Render a letter to PDF or Word document.

        Permission required: None

        A context dictionary may be provided that includes context variables that can be passed to the template.
        """
        try:
            subscription = Subscription.objects.get(pk=kwargs.get("pk"))
        except Subscription.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        context = {}
        context.update(settings.DEFAULT_TEMPLATE_PARAMETERS)
        context.update(request.data.get("context", {}))
        if request.accepted_renderer.format == "pdf":
            pdf = render_deregister_letter_pdf(context, subscription)
            return Response(
                status=status.HTTP_200_OK, data=pdf, content_type="application/pdf"
            )
        else:
            docx = render_deregister_letter_docx(context, subscription)
            return Response(
                status=status.HTTP_200_OK,
                data=docx,
                content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )


class SubscriptionRenderEmailAPIView(APIView):
    """
    Subscription Render Email API View.

    Permission required: None

    Use this endpoint to render the email of a Subscription.
    """

    schema = CustomAutoSchema(
        request_schema={
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "example": {
                        x: "string" for x in settings.DEFAULT_TEMPLATE_PARAMETERS
                    },
                },
            },
        }
    )

    renderer_classes = [PlainTextRenderer]

    def post(self, request, **kwargs):
        """Get request."""
        try:
            instance = Subscription.objects.get(pk=kwargs.get("pk"))
        except Subscription.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        context = {}
        context.update(settings.DEFAULT_TEMPLATE_PARAMETERS)
        context.update(request.data.get("context", {}))
        email = render_deregister_email(
            context,
            instance,
        )
        return Response(
            status=status.HTTP_200_OK, data=email, content_type="text/plain"
        )


class TemplateAPIView(APIView):
    """
    Template API View.

    Permission required: is_staff

    Use this endpoint to render a user submitted template with a user submitted context.
    """

    schema = CustomAutoSchema(
        request_schema={
            "type": "object",
            "properties": {
                "source": {"type": "string", "example": "string"},
                "context": {"type": "object", "example": {"name": "string"}},
            },
        }
    )

    renderer_classes = [WordDocumentRenderer, PDFRenderer, PlainTextRenderer]
    permission_classes = [IsAdminUser]

    def post(self, request, **kwargs):
        """Render user submitted template."""
        if "source" not in request.data.keys() or "context" not in request.data.keys():
            return Response(status=status.HTTP_400_BAD_REQUEST)
        context_data = {
            "date": datetime.datetime.now().strftime("%d-%m-%Y"),
        }
        context_data.update(request.data["context"])
        if request.accepted_renderer.format == "pdf":
            try:
                pdf = render_string_to_pdf(request.data["source"], context_data)
            except (
                django.template.exceptions.TemplateSyntaxError,
                django.template.exceptions.TemplateDoesNotExist,
            ) as e:
                request.accepted_renderer = JSONRenderer()
                return Response(
                    status=status.HTTP_400_BAD_REQUEST,
                    data={"detail": e.__str__()},
                    content_type="application/json",
                )
            return Response(
                status=status.HTTP_200_OK, data=pdf, content_type="application/pdf"
            )
        else:
            try:
                text = render_string(request.data["source"], context_data)
            except (
                django.template.exceptions.TemplateSyntaxError,
                django.template.exceptions.TemplateDoesNotExist,
            ) as e:
                request.accepted_renderer = JSONRenderer()
                return Response(
                    status=status.HTTP_400_BAD_REQUEST,
                    data={"detail": e.__str__()},
                    content_type="application/json",
                )
            return Response(
                status=status.HTTP_200_OK, data=text, content_type="text/plain"
            )

website/subscriptions/templates/subscriptions/enter_information.html
{% extends "kanikervanaf/sidebar.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Uw gegevens
{% endblock %}

{% block page_description %}
    Vul uw persoonlijke informatie in zodat bedrijven uw abonnement kunnen opzeggen.
{% endblock %}

{% block content %}
    <div class="container-fluid mb-5">
        <h1 class="mb-5"><strong>Persoonlijke gegevens</strong></h1>
        <p>
            Vul hieronder uw persoonlijke gegevens in. Wij hebben uw gegevens nodig zodat wij uw persoonlijke
            opzegmails kunnen opstellen. Uw gegevens worden pas door de server verwerkt bij het verzenden van de
            verificatiemail. Nadat u uw mailadres heeft bevestigd worden uw gegevens direct verwijderd.
        </p>
        <form>
            {{ form }}
		</form>
    </div>
{% endblock %}

{% block sidebar %}
    {% include "subscriptions/subscription_list.html" with next_page="subscriptions:summary" button_enabled="details" scroller=False %}
{% endblock %}

{% block js %}
    <script src="{% static 'subscriptions/js/general.js' %}"></script>
    <script src="{% static 'subscriptions/js/details.js' %}"></script>
{% endblock %}

website/subscriptions/templates/subscriptions/mails_send.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Opzegmails
{% endblock %}

{% block page %}
    <div class="container mt-5">
        {% if succeeded %}
            <h1 class="text-center mb-5"><strong>Mails verzonden!</strong></h1>
            <p class="text-center">De opzegmails zijn verzonden! Ze komen over enkele ogenblikken aan in je mailbox.
                <br>
                <a class="btn btn-primary mt-3" href="{% url 'home' %}"><i class="fas fa-angle-double-left"></i> Terug naar homepagina</a>
            </p>
        {% else %}
            <h1 class="text-center mb-5"><strong>Mails verzenden mislukt!</strong></h1>
            <p class="text-center">Het verzenden van de overzichtsmail is mislukt, het kan zijn dat je wel opzegmails in je mailbox ontvangt.
            Mocht er iets ontbreken, probeer het later dan opnieuw of neem contact met ons op via
                <a href="mailto:klantenservice@kanikervanaf.nl">onze klantenservice</a>
                <br>
                <a class="btn btn-primary mt-3" href="{% url 'home' %}"><i class="fas fa-angle-double-left"></i> Terug naar homepagina</a>
            </p>
        {% endif %}
    </div>
{% endblock %}
{% if succeeded %}
    {% block js %}
        <script src="{% static 'subscriptions/js/general.js' %}"></script>
        <script>
            eraseAll();
        </script>
    {% endblock %}
{% endif %}

website/subscriptions/templates/subscriptions/subscription_details.html
{% extends "kanikervanaf/sidebar.html" %}
{% load static %}

{% block title %}
    {% if subscription %}
        Kanikervanaf: Contactgegevens {{ subscription.name }}
    {% else %}
        Kanikervanaf: Contactgegevens opzoeken
    {% endif %}
{% endblock %}

{% block page_description %}
    {% if subscription %}
        Bekijk de contactgegevens van {{ subscription.name }}.
    {% else %}
        Vind u het ook zo lastig om contactgegevens van bedrijven op te zoeken? Hier kunt u gemakkelijk en snel
        contactgegevens van bedrijven en abonnementen opzoeken.
    {% endif %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'subscriptions/css/categories.css' %}">
{% endblock %}

{% block content %}
    <script src="{% static 'subscriptions/js/general.js' %}"></script>
    <div class="container-xl mb-5">
        <h1>Contactgegevens abonnementdienst opzoeken</h1>
        <p>Contactgegevens van bedrijven die abonnementen aanbieden zijn vaak moeilijk te vinden op het internet. Dit willen
        wij veranderen! Wij maken het gemakkelijk om snel contactgegevens van bedrijven op te zoeken. Zoek hieronder naar
        een bedrijf en kijk of het bij ons in de database staat!</p>
        <div id="subscription-search">
            <input id="searchfor" type="text" maxlength="75" autocorrect="off" spellcheck="false" autocomplete="off"
       autocapitalize="off" placeholder="Zoek een abonnement..." class="container-fluid" v-on:keyup="set_timer"
           v-model="search_query" />
            <div id="selection-container-id" v-if="search_query != ''">
                <template v-if="subscriptions.length > 0">
                    <div v-for="subscription in subscriptions" class="menu-link">
                        <a :href="`{% url 'subscriptions:details_search' %}/${subscription.slug}`"><% subscription.name %></a>
                        <div class="icons">
                            <i v-if="has_price(subscription)" class='far fa-euro-sign'></i>
                            <i v-if="has_mail(subscription)" class='fas fa-at'></i>
                            <i v-if="has_letter(subscription)" class='far fa-envelope'></i>
                        </div>
                    </div>
                </template>
                <template v-else-if="subscriptions.length == 0">
                    <div class='menu-link'>
                        <p>
                            Dat abonnement is nog niet bij ons bekend! Door op de pijl te drukken kunt u doorgeven dat dit
                            abonnement nog niet in onze database staat. Wij zullen dan ons best doen om onze database aan te
                            vullen.
                        <p>
                        <a class='icons' style='cursor: pointer;' :href=`{% url 'subscriptions:request' %}?subscription=${search_query}`>
                            <i class='fas fa-arrow-right'></i>
                        </a>
                    </div>
                </template>
            </div>
        </div>
    </div>
    {% if subscription %}
        <div class="container-xl mb-5">
            <h2>{{ subscription.name }}</h2>
            {% if subscription.price %}
                <div class="subscription-detail">
                    <div class="subscription-icon">
                        <i class="fas fa-euro-sign"></i>
                    </div>
                    <p class="m-0">Prijs per jaar: €{{ subscription.price }}</p>
                </div>
            {% endif %}
            {% if subscription.support_email %}
                <div class="subscription-detail">
                    <div class="subscription-icon">
                        <i class="fas fa-at"></i>
                    </div>
                    <p class="m-0">E-mail adres klantenservice:
                        <a href="mailto:{{ subscription.support_email }}">{{ subscription.support_email }}</a>
                    </p>
                </div>
            {% endif %}
            {% if subscription.support_phone_number %}
                <div class="subscription-detail">
                    <div class="subscription-icon">
                        <i class="fas fa-phone"></i>
                    </div>
                    <p class="m-0">Telefoonnummer klantenservice:
                        <a href="tel:{{ subscription.support_phone_number }}">{{ subscription.support_phone_number }}</a>
                    </p>
                </div>
            {% endif %}
            {% if subscription.cancellation_number %}
                <div class="subscription-detail">
                    <div class="subscription-icon">
                        <i class="fas fa-sign-out-alt"></i>
                    </div>
                    <p class="m-0">Opzegnummer (gratis):
                        <a href="tel:{{ subscription.cancellation_number }}">{{ subscription.cancellation_number }}</a>
                    </p>
                </div>
            {% endif %}
            {% if subscription.correspondence_address and subscription.correspondence_postal_code %}
                <div class="subscription-detail">
                    <div class="subscription-icon">
                        <i class="fas fa-map-marker-alt"></i>
                    </div>
                    <p class="m-0">Correspondentie adres:
                        {{ subscription.correspondence_address }}, {{ subscription.correspondence_postal_code }}{% if subscription.correspondence_city %}, {{ subscription.correspondence_city }}{% endif %}
                    </p>
                </div>
            {% endif %}
            {% if subscription.support_reply_number and subscription.support_postal_code %}
                <div class="subscription-detail">
                    <div class="subscription-icon">
                        <i class="fas fa-address-card"></i>
                    </div>
                    <p class="m-0">Postbus klantenservice:
                        Postbus {{ subscription.support_reply_number }}, {{ subscription.support_postal_code }}{% if subscription.support_city %}, {{ subscription.support_city }}{% endif %}
                    </p>
                </div>
            {% endif %}
        </div>
        {% if subscription.explanation_field %}
            <div class="subscription-explanation">
                {{ subscription.explanation_field | safe }}
            </div>
        {% endif %}
    {% endif %}
{% endblock %}
{% block sidebar %}
    <div class="container-fluid">
        <h2>Meest opgezegde abonnementen</h2>
        <ol>
            {% for subscription in top_subscriptions %}
                <li><a href="{% url "subscriptions:details" subscription=subscription %}">{{ subscription.name }}</a></li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

{% block js %}
    <script>
        let subscription_details_search_vue = new Vue({
            el: '#subscription-search',
            delimiters: ['<%', '%>'],
            data: {
                subscriptions: [],
                search_query: "",
                typing_timer: null,
                loading: false,
            },
            methods: {
                set_timer() {
                    clearTimeout(this.typing_timer);
                    if (this.search_query) {
                        this.typing_timer = setTimeout(this.search, 200);
                    }
                },
                search() {
                    this.loading = true;
                    fetch(`{% url "v1:subscription_list" %}?search=${this.search_query}&page_size=5`)
                    .then(response => response.json())
                    .then(json => {
                        this.subscriptions = json.results;
                        this.loading = false;
                    });
                },
            }
        });
    </script>
{% endblock %}

website/subscriptions/templates/subscriptions/subscription_header.html
{% load static %}

<script src="{% static 'subscriptions/js/general.js' %}"></script>

<div class="container-fluid">
    <h1 class="mb-5"><strong>Selecteer abonnementen</strong></h1>
    <p>
        Zoek hieronder de abonnementen die u op wil zeggen of kies ze uit in de onderstaande top vijf
        per categorie. Aangeklikte abonnementen zullen verschijnen in de lijst met abonnementen die u
        op wilt zeggen. U kunt op "Volgende stap" klikken als u minimaal één abonnement hebt geselecteerd.
    </p>
    <p>
        Een email symbool (<i class="fas fa-at"></i>) achter een abonnement geeft aan dat wij de gegevens
        van het bedrijf hebben om een e-mail op te kunnen stellen. Een brief symbool
        (<i class="fas fa-envelope"></i>) geeft aan dat wij de gegevens van het bedrijf hebben om een
        opzegbrief te kunnen genereren. De e-mails en opzegbrieven worden in stap 3 naar u verstuurd
        via e-mail. Een euro symbool (<i class="fas fa-euro-sign"></i>) geeft aan dat wij een geregistreerde prijs
        hebben voor het abonnement, die prijs zult u in het totaal terug zien.
    </p>
</div>
<div id="subscription-search">
    <input id="searchfor" type="text" maxlength="75" autocorrect="off" spellcheck="false" autocomplete="off"
       autocapitalize="off" placeholder="Zoek een abonnement..." class="container-fluid" v-on:keyup="set_timer"
           v-model="search_query" />
    <div id="selection-container-id" v-if="search_query != ''">
        <template v-if="subscriptions.length > 0">
            <div v-for="subscription in subscriptions" class="menu-link">
                <input name="checkbox-search-list" type="checkbox" class="normal-checkbox" v-on:click="toggle_checkbox(this, subscription, in_list(selectedSubscriptions, subscription.id))" :checked="in_list(selectedSubscriptions, subscription.id)" :id="`checkbox-search-${subscription.id}`"></input>
                <label :for="`checkbox-search-${subscription.id}`"><% subscription.name %></label>
                <div class="icons">
                    <i v-if="has_price(subscription)" class='far fa-euro-sign'></i>
                    <i v-if="has_mail(subscription)" class='fas fa-at'></i>
                    <i v-if="has_letter(subscription)" class='far fa-envelope'></i>
                </div>
            </div>
        </template>
        <template v-else-if="subscriptions.length == 0">
            <div class='menu-link'>
                <p>
                    Dat abonnement is nog niet bij ons bekend! Door op de pijl te drukken kunt u doorgeven dat dit
                    abonnement nog niet in onze database staat. Wij zullen dan ons best doen om onze database aan te
                    vullen.
                <p>
                <a class='icons' style='cursor: pointer;' :href=`{% url 'subscriptions:request' %}?subscription=${search_query}`>
                    <i class='fas fa-arrow-right'></i>
                </a>
            </div>
        </template>
    </div>
</div>

<script>
    let subscription_search_vue = new Vue({
        el: '#subscription-search',
        delimiters: ['<%', '%>'],
        data: {
            subscriptions: [],
            search_query: "",
            typing_timer: null,
            loading: false,
            selectedSubscriptions: [],
        },
        created() {
            this.refresh();
        },
        methods: {
            set_timer() {
                clearTimeout(this.typing_timer);
                if (this.search_query) {
                    this.typing_timer = setTimeout(this.search, 200);
                }
            },
            search() {
                this.loading = true;
                fetch(`{% url "v1:subscription_list" %}?search=${this.search_query}&page_size=5`)
                .then(response => response.json())
                .then(json => {
                    this.subscriptions = json.results;
                    this.loading = false;
                });
            },
            toggle_checkbox(checkbox, subscription, checked) {
                let list = get_list();
                if (!checked) {
                    if (!in_list(list, subscription.id)) {
                        list.push({"id": subscription.id, "price": parseFloat(subscription.price), "name": subscription.name, "has_email": has_mail(subscription), "has_letter": has_letter(subscription), "has_price": has_price(subscription)});
                    }
                }
                else {
                    let newlist = [];
                    for (let i = 0; i < list.length; i++) {
                        if (list[i].id !== subscription.id) {
                            newlist.push(list[i]);
                        }
                    }
                    list = newlist;
                }
                set_list(list);
                refresh_all();
            },
            refresh() {
                this.selectedSubscriptions = get_list();
            }
        }
    });
</script>