website/kanikervanaf/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    IndexView,
    ContactView,
    FAQView,
    PrivacyPolicy,
    handler404 as custom_handler404,
    handler500 as custom_handler500,
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomeSitemap, ContactSitemap, FAQSitemap, PrivacySitemap
from posts.sitemaps import PostOverviewSitemap, PostCreateSitemap, PostDetailsSitemap
from subscriptions.sitemaps import (
    SubscriptionCategoryPageSitemap,
    SubscriptionListSitemap,
    SubscriptionDetailsSearchSitemap,
    SubscriptionDetailsSitemap,
    SubscriptionSummarySitemap,
    SubscriptionRequestSitemap,
    EnterUserSitemap,
)
from users.sitemaps import UserSitemap

sitemaps = {
    "home": HomeSitemap,
    "contact": ContactSitemap,
    "faq": FAQSitemap,
    "privacy": PrivacySitemap,
    "posts:post_create": PostCreateSitemap,
    "posts:post_overview": PostOverviewSitemap,
    "posts:details": PostDetailsSitemap,
    "subscriptions:overview": SubscriptionListSitemap,
    "subscriptions:overview_category_page": SubscriptionCategoryPageSitemap,
    "subscriptions:summary": SubscriptionSummarySitemap,
    "subscriptions:requets": SubscriptionRequestSitemap,
    "subscriptions:details_search": SubscriptionDetailsSearchSitemap,
    "subscriptions:details": SubscriptionDetailsSitemap,
    "subscriptions:enter": EnterUserSitemap,
    "users": UserSitemap,
}

handler404 = custom_handler404
handler500 = custom_handler500

urlpatterns = [
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="home"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("faq", FAQView.as_view(), name="faq"),
    path("privacybeleid", PrivacyPolicy.as_view(), name="privacy"),
    path("contact", ContactView.as_view(), name="contact"),
    path("admin/", admin.site.urls),
    path(
        "subscriptions/",
        include(("subscriptions.urls", "subscriptions"), namespace="subscriptions"),
    ),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("api/", include("kanikervanaf.api.urls")),
]

website/posts/urls.py
from django.urls import path, register_converter
from .views import PostOverviewView, PostCreateView, PostDetailsView, PostUserOverview
from .converters import PostConverter

register_converter(PostConverter, "post")

urlpatterns = [
    path("overview/page/<int:page>", PostOverviewView.as_view(), name="post_overview"),
    path("create", PostCreateView.as_view(), name="post_create"),
    path(
        "details/<post:post>/page/<int:page>", PostDetailsView.as_view(), name="details"
    ),
    path(
        "messages/page/<int:page>",
        PostUserOverview.as_view(),
        name="post_user_overview",
    ),
]

website/users/urls.py
from django.urls import path
from .views import (
    LoginView,
    RegisterView,
    ForgotView,
    LogoutView,
    ResetView,
    AccountView,
    EmailConfirmView,
)

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", RegisterView.as_view(), name="register"),
    path("forgot", ForgotView.as_view(), name="forgot"),
    path("reset/<str:token>", ResetView.as_view(), name="reset"),
    path("update/<str:token>", EmailConfirmView.as_view(), name="confirm"),
    path("account", AccountView.as_view(), name="account"),
]

website/users/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.http import Http404

from .forms import (
    UserLoginForm,
    UserRegisterForm,
    PasswordForgotForm,
    PasswordResetForm,
    PasswordUpdateForm,
    UserUpdateForm,
    EmailUpdateForm,
)
from .models import User, PasswordReset, EmailUpdate
from .services import generate_password_reset, send_reset_password, send_update_email


class LoginView(TemplateView):
    """View for logging in."""

    template_name = "users/login.html"

    def get(self, request, **kwargs):
        """
        GET request for login view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the login page or a redirect to the next parameter or home page
        """
        next_page = request.GET.get("next")
        if request.user.is_authenticated:
            if next_page:
                return redirect(next_page)
            return redirect("/")

        form = UserLoginForm(None)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        POST request for login view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the login page or a redirect to next or the home page
        """
        next_page = request.GET.get("next")
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            login(request, user)
            if next_page:
                return redirect(next_page)
            return redirect("/")
        context = {"form": form}
        return render(request, self.template_name, context)


class RegisterView(TemplateView):
    """Registration view."""

    template_name = "users/register.html"

    def get(self, request, **kwargs):
        """
        GET request for registration view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the registration page or a redirect to the next parameter or home page
        """
        next_page = request.GET.get("next")
        if request.user.is_authenticated:
            if next_page:
                return redirect(next_page)
            return redirect("/")

        form = UserRegisterForm(None)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        POST request for registration view.

        This function registers a new user
        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the registration page
        """
        if request.user.is_authenticated:
            return redirect("/")

        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get("password")
            user.set_password(password)
            user.save()
            new_user = authenticate(username=user.email, password=password)
            login(request, new_user)
            return render(request, self.template_name, {"succeeded": True})

        context = {"form": form}

        return render(request, self.template_name, context)


class ForgotView(TemplateView):
    """Forgot password view."""

    template_name = "users/forgot.html"

    def get(self, request, **kwargs):
        """
        GET request for forgot password view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the forgot password page
        """
        form = PasswordForgotForm(None)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        POST request for login view.

        This function generates a PasswordReset object and sends a password reset email
        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the forgot password page
        """
        form = PasswordForgotForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            if User.objects.filter(email=email).exists():
                user = User.objects.get(email=email)
                reset = generate_password_reset(user)
                send_reset_password(reset, request)
            return render(request, self.template_name, {"succeeded": True})
        context = {"form": form}
        return render(request, self.template_name, context)


class LogoutView(TemplateView):
    """Log out view."""

    template_name = "users/logout.html"

    def get(self, request, **kwargs):
        """
        GET request for logout view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the logout page or a redirect to the next parameter or home page
        """
        next_page = request.GET.get("next")
        if request.user.is_authenticated:
            logout(request)
            if next_page:
                return redirect(next_page)
            return render(request, self.template_name)
        else:
            if next_page:
                return redirect(next_page)
            return redirect("/")


class ResetView(TemplateView):
    """Reset password view."""

    template_name = "users/reset.html"

    def get(self, request, **kwargs):
        """
        GET request for reset password view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the reset password page
        """
        form = PasswordResetForm(None)
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        POST request for reset password view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the reset password page
        """
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get("password")
            token = kwargs.get("token")
            PasswordReset.remove_expired()
            if PasswordReset.objects.filter(token=token).exists():
                reset = PasswordReset.objects.get(token=token)
                reset.user.set_password(new_password)
                reset.user.save()
                reset.delete()
                return render(request, self.template_name, {"succeeded": True})
            else:
                return render(request, self.template_name, {"failed": True})

        context = {"form": form}
        return render(request, self.template_name, context)


class EmailConfirmView(TemplateView):
    """Confirm email view."""

    template_name = "users/confirm.html"

    def get(self, request, **kwargs):
        """
        GET request for confirm email view.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the email confirmation page
        """
        token = kwargs.get("token")
        EmailUpdate.remove_expired()
        if EmailUpdate.objects.filter(token=token).exists():
            update = EmailUpdate.objects.get(token=token)
            update.update_user()
            update.delete()
            return render(request, self.template_name)
        else:
            raise Http404("Page not found")


class AccountView(LoginRequiredMixin, TemplateView):
    """Account details page, requires logged in user."""

    template_name = "users/account.html"

    def get(self, request, **kwargs):
        """
        GET method for account details page.

        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the accounts page with initial information filled in
        """
        password_form = PasswordUpdateForm()
        user_form = UserUpdateForm(user=request.user)
        email_form = EmailUpdateForm(user=request.user)

        context = {
            "form_password": password_form,
            "form_user": user_form,
            "form_email": email_form,
            "email_update": EmailUpdate.objects.filter(user=request.user).exists(),
        }

        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        """
        POST method for account details page.

        Changes details of a user account
        :param request: the request
        :param kwargs: keyword arguments
        :return: a render of the accounts page
        """
        form_type = request.POST.get("type")
        context = {"form_password": PasswordUpdateForm(), "messages": []}
        if form_type == "form_user":
            if self.handle_user_information_change(request):
                context["messages"].append(
                    {"error": False, "message": "Persoonlijke gegevens bijgewerkt"}
                )
            else:
                context["messages"].append(
                    {
                        "error": True,
                        "message": "Persoonlijke gegevens bijwerken mislukt",
                    }
                )
        elif form_type == "form_password":
            if self.handle_password_change(request):
                context["messages"].append(
                    {"error": False, "message": "Wachtwoord bijgewerkt"}
                )
            else:
                context["messages"].append(
                    {"error": True, "message": "Wachtwoord bijwerken mislukt"}
                )

website/users/templates/users/account-sidebar.html
<ul>
    <li><a href="{% url "posts:post_user_overview" page=1 %}">Mijn berichten</a></li>
    <li><a href="{% url "users:account" %}">Mijn account</a></li>
    <li><a href="{% url "users:logout" %}">Uitloggen</a></li>
</ul>

website/users/templates/users/account.html
{% extends "kanikervanaf/sidebar.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Account
{% endblock %}

{% block page_description %}
    Bekijk uw accountgegevens.
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'users/css/centered-container.css' %}"/>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <h1><strong>Mijn account</strong></h1>
        <p>Gebruikersnaam: {{ user.username }}</p>
        {% for message in messages %}
            <p class="{% if message.error %}message-error{% else %}message-ok{% endif %}">{{ message.message }}</p>
        {% endfor %}
        <h3>Email-adres wijzigen</h3>
        {% if email_update %}
            <p class="message-ok">Er is momenteel een email update actief, klik op de link in de mail om je email-adres aan te passen.</p>
        {% endif %}
        <form method="POST" class="centered-form">
            {% csrf_token %}
            {{ form_email }}
            <input type="hidden" name="type" value="form_email"/>
            <input type="submit" class="btn btn-primary" value="Email-adres wijzigen"/>
        </form>
        <h3>Wachtwoord wijzigen</h3>
        <form method="POST" class="centered-form">
            {% csrf_token %}
            {{ form_password }}
            <input type="hidden" name="type" value="form_password"/>
            <input type="submit" class="btn btn-primary" value="Wachtwoord wijzigen"/>
        </form>
        <h3>Persoonlijke gegevens wijzigen</h3>
        <form method="POST" class="centered-form">
            {% csrf_token %}
            {{ form_user }}
            <input type="hidden" name="type" value="form_user"/>
            <input type="submit" class="btn btn-primary" value="Gegevens wijzigen"/>
        </form>
    </div>
{% endblock %}
{% block sidebar %}
    {% include 'users/account-sidebar.html' %}
{% endblock %}

website/users/templates/users/confirm.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Email bevestigen
{% endblock %}

{% block styles %}
    <link href="{% static "users/css/centered-container.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
        </div>
    </nav>
{% endblock %}

{% block page %}
    <div class="container-sm d-flex align-items-center justify-content-center">
        <div style="max-width: 400px">
            <h1>Email bevestigd</h1>
            <p class="message-ok">Uw email adres is aangepast.</p>
            <a href="{% url "home" %}"> ← Terug naar Kanikervanaf.nl</a>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

website/users/templates/users/enter_information.html
{% extends "kanikervanaf/sidebar.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Uw gegevens
{% endblock %}

{% block page_description %}
    Vul uw persoonlijke informatie in zodat bedrijven uw abonnement kunnen opzeggen.
{% endblock %}

{% block content %}
    <div class="container-fluid mb-5">
        <h1 class="mb-5"><strong>Persoonlijke gegevens</strong></h1>
        <p>
            Vul hieronder uw persoonlijke gegevens in. Wij hebben uw gegevens nodig zodat wij uw persoonlijke
            opzegmails kunnen opstellen. Uw gegevens worden pas door de server verwerkt bij het verzenden van de
            verificatiemail. Nadat u uw mailadres heeft bevestigd worden uw gegevens direct verwijderd.
        </p>
        <form>
            {{ form }}
		</form>
    </div>
{% endblock %}

{% block sidebar %}
    {% include "subscriptions/subscription_list.html" with next_page="subscriptions:summary" button_enabled="details" scroller=False %}
{% endblock %}

{% block js %}
    <script src="{% static 'subscriptions/js/general.js' %}"></script>
    <script src="{% static 'users/js/details.js' %}"></script>
{% endblock %}

website/users/templates/users/forgot.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Wachtwoord vergeten
{% endblock %}

{% block styles %}
    <link href="{% static "users/css/centered-container.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
        </div>
    </nav>
{% endblock %}

{% block page %}
    <div class="container-sm d-flex align-items-center justify-content-center">
        <div style="max-width: 400px">
            <h1>Wachtwoord vergeten</h1>
            {% if succeeded %}
                <p class="message-ok">De verificatiemail is verzonden, druk op de link in je mailbox om je wachtwoord te herstellen</p>
            {% else %}
                <p>Vul hieronder je email adres in, wij zullen je een mailtje sturen waarmee
                je je wachtwoord kan herstellen.</p>
                <form method="POST" class="centered-form">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" class="btn btn-primary"/>
                </form>
            {% endif %}
            <div class="container-fluid mb-3">
                <a class="text-center" href="{% url "users:login" %}">Inloggen</a> |
                <a class="text-center" href="{% url "users:register" %}">Registreren</a>
            </div>
            <a href="{% url "home" %}"> ← Terug naar Kanikervanaf.nl</a>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

website/users/templates/users/login.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Inloggen
{% endblock %}

{% block styles %}
    <link href="{% static "users/css/centered-container.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
        </div>
    </nav>
{% endblock %}

{% block page %}
    <div class="container-sm d-flex align-items-center justify-content-center">
        <div style="max-width: 400px">
            <h1>Login</h1>
            <form method="POST" class="centered-form">
                {% csrf_token %}
                {{ form }}
                <input type="submit" class="btn btn-primary"/>
            </form>
            <div class="container-fluid mb-3">
                <a class="text-center" href="{% url "users:register" %}">Registreren</a> |
                <a class="text-center" href="{% url "users:forgot" %}">Wachtwoord vergeten</a>
            </div>
            <a href="{% url "home" %}"> ← Terug naar Kanikervanaf.nl</a>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

website/users/templates/users/logout.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Uitgelogd
{% endblock %}

{% block styles %}
    <link href="{% static "users/css/centered-container.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
        </div>
    </nav>
{% endblock %}

{% block page %}
    <div class="container-sm d-flex align-items-center justify-content-center">
        <div style="max-width: 400px">
            <h1>Je bent uitgelogd</h1>
            <div class="container-fluid mb-3">
                <a class="text-center" href="{% url "users:login" %}">Inloggen</a> |
                <a class="text-center" href="{% url "users:register" %}">Registreren</a> |
                <a class="text-center" href="{% url "users:forgot" %}">Wachtwoord vergeten</a>
            </div>
            <a href="{% url "home" %}"> ← Terug naar Kanikervanaf.nl</a>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

website/users/templates/users/register.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Registreren
{% endblock %}

{% block styles %}
    <link href="{% static "users/css/centered-container.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
        </div>
    </nav>
{% endblock %}

{% block page %}
    <div class="container-sm d-flex align-items-center justify-content-center">
        <div style="max-width: 400px">
            <h1>Registreer</h1>
            {% if succeeded %}
                <p class="message-ok">Je account is aangemaakt</p>
            {% else %}
                <form method="POST" class="centered-form">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" class="btn btn-primary"/>
                </form>
            {% endif %}
            <div class="container-fluid mb-3">
                <a class="text-center" href="{% url "users:login" %}">Inloggen</a> |
                <a class="text-center" href="{% url "users:forgot" %}">Wachtwoord vergeten</a>
            </div>
            <a href="{% url "home" %}"> ← Terug naar Kanikervanaf.nl</a>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

website/users/templates/users/reset.html
{% extends "kanikervanaf/base.html" %}
{% load static %}

{% block title %}
    Kanikervanaf: Wachtwoord vergeten
{% endblock %}

{% block styles %}
    <link href="{% static "users/css/centered-container.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand-md navbar-light sticky-top site-header mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'kanikervanaf/img/logo.png' %}" height="50"/></a>
        </div>
    </nav>
{% endblock %}

{% block page %}
    <div class="container-sm d-flex align-items-center justify-content-center">
        <div style="max-width: 400px">
            <h1>Wachtwoord herstellen</h1>
            {% if succeeded %}
                <p class="message-ok">Het wachtwoord is aangepast!</p>
            {% elif failed %}
                <p class="message-error">Het wachtwoord is niet aangepast</p>
            {% else %}
                <form method="POST" class="centered-form">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" class="btn btn-primary"/>
                </form>
            {% endif %}
            <div class="container-fluid mb-3">
                <a class="text-center" href="{% url "users:login" %}">Inloggen</a> |
                <a class="text-center" href="{% url "users:register" %}">Registreren</a>
            </div>
            <a href="{% url "home" %}"> ← Terug naar Kanikervanaf.nl</a>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}